config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'career', to: 'static_pages#career'
  get 'team', to: 'static_pages#team'
  get 'about', to: 'static_pages#about'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
  
  mount_uploader :image, ImageUploader

   def free?
    cost.zero?
  end

  def premium?
    ! free?
  end

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id


   def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons


  include RankedModel
    ranks :row_order, with_same: :course_id

    def next_section
      section = course.section.where("row_order > ?", self.row_order).rank(:row_order).first
      return section
    end

    def previous_section
      section = course.sections.where("row_order < ?", self.row_order).rank(:row_order).last
      return section
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Premo Content',
        currency: 'usd'
      )
    end

  current_user.enrollments.create(course: current_course)
  redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
       if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end


  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
    def current_course
      @current_course ||= Course.find(params[:id])
    end


  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update 
    current_lesson.update_attributes(lesson_params)
    render plain: 'Updated!'
  end


  private

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end


  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

 

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render plain: 'updated!'
  end


  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end


  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end


  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrollment_for_current_lesson


  def show
  end

  private

  def require_authorized_for_current_lesson
    if current_lesson.user != current_user
      redirect_to course_sections, alert: 'Error Message Here'
    end
  end

  def require_enrollment_for_current_lesson
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert: "You must enroll."
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index 
  end

  def privacy
  end

  def team
  end

  def career
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn Something Today</h1>
  <hr />

  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
      <%= image_tag course.image.to_s, class: 'img-fluid' %>
    <br />
    </h2>
      <br />
    <div class="row">
        <div class="col-sm-8 col-12">
          <%= course.description %>
        </div>
      <div class="col-sm-4 col-12 text-center">
          <%= link_to 'More Details', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clr" />
    <% end %>
</div>

app/views/courses/show.html.erb


<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <br />
   <%= image_tag @course.image.url, class: 'img-fluid' %>
    <br />
    <div class="row">
     <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>
        <% if current_user && current_user == @course.user %>
          <br />
          <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>

      <br />
      <br />
       <% if current_user %>
    <% if current_user.enrolled_in?(@course) %>
      <h3 class="badge badge-info">You Are Enrolled!</h3>
    <% else %>
      <% if @course.free? %>
        <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
      <% else %>
        <%= form_tag course_enrollments_path(@course) do %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-email="<%= current_user.email %>"
                  data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                  data-amount="<%= (@course.cost * 100).to_i %>"
                  data-locale="auto"></script>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <h3 class="badge badge-info">Sign In to Enroll!</h3>
  <% end %>
    </div>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
 </div>
</div>

<div class="col-12">
    <% @course.sections.each do |section| %>
    <br /> <br />
      <div class="section">
        <h3>
        <%= section.title %>
        </h3>
        <div class="row">
        <% section.lessons.rank(:row_order).each do |lesson| %>
            <div class="col-12 col-sm-6">
              <div class="lesson text-center">
                <br />
                <%= link_to lesson_path(lesson) do %>
                  <b><%= lesson.title %></b>
                  <br />
                  <%= lesson.subtitle %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <br class="clear">
      </div>
    <% end %>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb

<script>
  $(function() {
   $('.new-lesson-button').click(function( event ) {
  var lessonUrl = $( event.target).data('lesson-url');
  $('#newLessonForm').attr('action', lessonUrl);
});

    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });


    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });

  });
</script>


<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
    <br />
    <%= image_tag current_course.image.url, class: 'img-fluid' %>

    <br />
  <%= link_to 'Preview As Student...', course_path(current_course), class: 'btn btn-warning float-right' %>
    <br class="clr" />
  <div class="text-center">
   <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
  Add A new section
</button>
  </div>


   <ul class="sections">
<% current_course.sections.rank(:row_order).each do |section| %>
  <li data-update-url="<%= instructor_section_path section %>" class="section-li">
    <div class="header float-left">
      <span class="fa fa-ellipsis-v"></span>
      <%= section.title %>
    </div>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg float-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
  New Lesson...
</button>
    <br class="clr" />
    <br class="clr" />


    <ul class="lessons">
  <% section.lessons.rank(:row_order).each do |lesson| %>
    <li data-update-url="<%= instructor_lesson_path lesson %>">
      <div class="row">
        <div class="col-1">
          <span class="fa fa-ellipsis-v"></span>
        </div>
        <div class="col-11 text-center">
          <p>
            <b><%= lesson.title %></b>
          </p>
          <p>
            <%= lesson.subtitle %>
          </p>
        </div>
      </div>
      <br class="clr" />
      <% end %>
    </li>
  <% end %>
</ul>
</div>



<!-- Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new section</h4>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a section", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>






<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |f| %>
      <div class="modal-body">
          
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
          <br />
          
          <br />
          <br />
        
      </div>
      <div class="modal-footer">
        
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p class="float-left">
    <%= current_lesson.subtitle %>
  </p>

<% if current_lesson.next_lesson.present? %>
  <%= link_to lesson_path(current_lesson.next_lesson), class: 'btn btn-default' do %>
    Next Lesson &nbsp; 
    <span class="fa fa-forward"></span>
  <% end %>
<% end %>


  <video id="my-video" class="video-js vjs-big-play-centered vjs-fluid" controls preload="auto" width="auto" height="aut0"
   poster="<%= image_path('black.jpg') %>" data-setup="{}">
    <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
    <source src="MY_VIDEO.webm" type='video/webm'>
      <noscript>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </noscript>
  </video>
</div>